config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"

 }


namespace :admin do
    get 'top' => 'homes#top'
    resources :members, only:[:index, :show, :edit, :update]

    resources :orders, only:[:index, :show, :update]



    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    get 'search' => 'products#search'
  end




  root 'member/homes#top'

  devise_for :member,skip: [:passwords,], controllers: {
  registrations: "member/registrations",
  sessions: 'member/sessions'
  }

  scope module: :member do
    resources :products, only: [:index, :show]
    get 'homes/about'
    get 'members/show'
    get 'members/edit'
    get 'members/unsubscribe'
    patch 'members/update'
    patch 'members/withdraw'
    delete "cart_products/destroy_all" => "cart_products#destroy_all"
    resources :cart_products, only: [:index, :create, :update, :destroy]
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]

    resources :products, only: [:index, :show]

    get "orders/new" => "orders#new"
    get "orders/confirm" => "orders#confirm"
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:index, :show, :create]



  end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details,dependent: :destroy

    belongs_to :member

    has_many :products,through: :order_details,source: :product

    enum payment_method: { credit_card:0, transfer:1 }

    enum status: {
        payment_waiting:0,#入金待ち
        payment_confirmation:1,#入金確認
        in_production:2,#製作中
        preparing_delivery:3,#発送準備中
        delivered:4 #発送済み
    }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

     def index
       @orders = Order.page(params[:page]).per(10).reverse_order
     end

     def show
       @order = Order.find(params[:id])
       @order_products = @order.order_details
     end

     def update
       @order = Order.find(params[:id])
       @order.update(order_params)
       @order_products = @order.order_details
       if @order.status == "payment_confirmation"
          @order_products.each do |order_product|
            order_product.maiking_status = "production_pending"
            order_product.save
          end
       end
        redirect_to admin_order_path(@order.id)
     end


    private
        def order_params
          params.require(:order).permit(:status)
        end

        def order_details_params
          params.require(:order_details).permit(:maiking_status)
        end

end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
  def new
    @order = Order.new
    @member = current_member
    @addresses = @member.shipping_addresses
  end

  def create
  	member = current_member
  	# sessionを使ってデータを一時保存
  	session[:order] = Order.new
  	cart_products = current_member.cart_products

  	# total_paymentのための計算
  	sum = 0
  	cart_products.each do |cart_product|
  		sum += (cart_product.product.add_tax_price).floor * cart_product.amount
  	end

  	session[:order][:postage] = 800
  	#送料込みの合計金額
  	session[:order][:billing_amount] = sum + session[:order][:postage]
  	#注文ステータス
  	session[:order][:status] = 0
  	session[:order][:member_id] = current_member.id
  	# ラジオボタンで選択された支払方法のenum番号を渡している
  	session[:order][:payment_method] = params[:payment_method].to_i

  	# ラジオボタンで選択されたお届け先によって条件分岐
  	destination = params[:a_method].to_i
  	# ご自身の住所が選択された時
  	if destination == 0
  		session[:order][:postal_code] = member.postal_code
  		session[:order][:address] = member.address
  		session[:order][:name] = member.last_name + member.first_name
  		# 登録済住所が選択された時
  	elsif destination == 1
  		address = ShippingAddress.find(params[:address_for_order])
  		session[:order][:postal_code] = address.postal_code.to_i
  		session[:order][:address] = address.address
  		session[:order][:name] = address.name
  	# 新しいお届け先が選択された時
  	elsif destination == 2
  		session[:new_address] = 2
  		session[:order][:postal_code] = params[:postal_code].to_i
  		session[:order][:address] = params[:address]
  		session[:order][:name] = params[:name]
  	end
  	# お届け先情報に漏れがあればリダイレクト
  	if session[:order][:postal_code].presence && session[:order][:address].presence && session[:order][:name].presence
      redirect_to orders_confirm_path
  	else
  		flash[:alert] = 'お届け先情報を入力してください'
  		redirect_to orders_new_path
  	end
  end

  def confirm
    @cart_products = current_member.cart_products.page(params[:page]).per(4)
  end


  def complete
  	order = Order.new(session[:order])
	  order.save

		# 新しいお届け先を自動で保存
		if session[:new_address]
			address = current_member.shipping_addresses.new
			address.postal_code = order.postal_code
			address.address = order.address
			address.name = order.name
			address.save
			session[:new_address] = nil
		end
		# 以下、order_detail(中間テーブル)作成
		cart_products = current_member.cart_products
		cart_products.each do |cart_product|
		order_detail = OrderDetail.new
		order_detail.order_id = order.id
		order_detail.product_id = cart_product.product.id
		order_detail.amount = cart_product.amount
		order_detail.maiking_status = 0
		order_detail.price = (cart_product.product.add_tax_price).floor
		order_detail.save
		end
		session.delete(:order)
		session[:order] = nil
		# 購入後はカート内商品削除
		cart_products.destroy_all
  end

  def index
  	@orders = current_member.orders.page(params[:page]).per(6)
  end

  def show
  	@order = Order.find(params[:id])
  	@order_details = @order.order_details
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container order-index">
  <div class="row mt-4">
    <div class="row col-8">
      <p class="col-2"></p>
      <p class="col-4 fs-5 bg-light text-center">注文履歴一覧</p>
    </div>

    <div class="row col-8 mx-auto">
      <table class='table table-hover table-inverse '>
        <thead class="bg-light">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime('%Y/%m/%d　%H:%M:%S'),admin_order_path(order) %></td>
            <td><%= order.name %></td>
            <td>
                <%= order.order_details.sum(:amount) %>
            </td>
            <td><%= order.status_i18n %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
    </div>
  </div>
 </div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="admin-heading col-md-12">
      <h3 class="mb-4 col-3 pt-2 pb-2">注文履歴詳細</h3>
    </div>
    <table class="table table-sm mb-3 admin-order-show-table">
      <tbody>
        <tr>
          <th>購入者</th>
          <td><%= link_to "#{@order.member.last_name} #{@order.member.first_name}", admin_members_path(@order.member.id), class: "text-dark border-bottom border-dark" %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
            <%= f.select :status, [["入金待ち","payment_waiting"], ["入金確認","payment_confirmation"], ["製作中","in_production"], ["発送準備中","preparing_delivery"], ["発送済み","delivered"]], class: "form-control" %>

              <%= f.submit "更新", class: "btn ml-3 btn-dark btn-sm" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row mb-5">
    <div class="col-7">
      <table class="table mt-3 table-borderless table-hover rounded-top rounded-bottom table_border_radius admin-order-table">
        <thead class="thead-dark">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @sum = 0 %>
          <% @order_products.each do |order_product| %>
          <tr>
            <td><%= order_product.product.name %></td>
            <td><%= order_product.product.add_tax_price %></td>
            <td><%= order_product.amount %></td>
            <td>
              <% @products_price = order_product.product.add_tax_price * order_product.amount %>
              <%= @products_price %>
            </td>
            <td>
              <%= form_with model: order_product, url: admin_order_detail_path(order_product), method: :patch, local: true do |f| %>
                <%= f.select :maiking_status , [["着手不可", "production_not_possible"], ["製作待ち", "production_pending"], ["製作中", "in_production"], ["製作完了", "production_complete"]], class: "form-control" %>
                <%= f.submit "更新", class: "btn ml-3 btn-dark btn-sm" %>
              <% end %>
            </td>
            <% @sum += @products_price %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @sum %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td>800円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @sum + 800 %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>