config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"

 }


namespace :admin do
    get 'top' => 'homes#top'
    resources :members, only:[:index, :show, :edit, :update]

    resources :orders, only:[:index, :show, :update]



    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    get 'search' => 'products#search'
  end




  root 'member/homes#top'

  devise_for :member,skip: [:passwords,], controllers: {
  registrations: "member/registrations",
  sessions: 'member/sessions'
  }

  scope module: :member do
    resources :products, only: [:index, :show]
    get 'homes/about'
    get 'members/show'
    get 'members/edit'
    get 'members/unsubscribe'
    patch 'members/update'
    patch 'members/withdraw'
    delete "cart_products/destroy_all" => "cart_products#destroy_all"
    resources :cart_products, only: [:index, :create, :update, :destroy]
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]

    resources :products, only: [:index, :show]

    get "orders/new" => "orders#new"
    get "orders/confirm" => "orders#confirm"
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:index, :show, :create]



  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
 
  belongs_to :member
  belongs_to :product
  
  #商品の税込価格を出すメソッド
  def add_tax_price
    (self.product.price * 1.10).round
  end
  
  #商品毎の合計金額を出すメソッド
  def sub_price
      add_tax_price * self.amount
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord

 has_many :products, dependent: :destroy
  validates :name, {presence: true}




end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_products, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders,dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end


end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details,dependent: :destroy

    belongs_to :member

    has_many :products,through: :order_details,source: :product

    enum payment_method: { credit_card:0, transfer:1 }

    enum status: {
        payment_waiting:0,#入金待ち
        payment_confirmation:1,#入金確認
        in_production:2,#製作中
        preparing_delivery:3,#発送準備中
        delivered:4 #発送済み
    }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :product

   enum maiking_status: {
     production_not_possible:0,#制作不可
     production_pending:1,#制作待ち
     in_production:2,#製作中
     production_complete:3#制作完了
 }

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :order_details, dependent: :destroy

  
  has_many :cart_products, dependent: :destroy
  has_many :orders,through: :order_details,source: :order,dependent: :destroy
  attachment :image

  def add_tax_price
    (self.price * 1.10).round
  end

def self.search(keyword)
  where(["name like? OR name like?", "%#{keyword}%", "%#{keyword}%"])
end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :member

  def address_all
   "〒" + self.postal_code + " " + self.address + " " + self.name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
before_action :authenticate_admin!

 def index
  @products = Product.all
  @products = Product.page(params[:page]).per(10)
 end

 def show
  @product = Product.find(params[:id])
 end

 def edit
  @product = Product.find(params[:id])
 end

 def update
  @product = Product.find(params[:id])
  if @product.update(product_params)
     redirect_to admin_product_path
  else
   flash[:error] = "入力してください"
      redirect_to 'edit'
  end
 end

 def new
  @product = Product.new

 end

 def create
  @product = Product.new(product_params)
  if @product.save

      redirect_to admin_product_path(@product.id)
  else
      render action: :new, danger: '登録に失敗しました'
  end
 end

 def destroy
 end

def search
  @products = Product.search(params[:keyword])
  @keyword = params[:keyword]
  render "search"
end


  private

  def product_params
    params.require(:product).permit(:genre_id, :name, :introduction, :is_active, :image, :price )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
      case resource
       when Admin
           admin_members_path
       when Member
           members_show_path(resource)
      end
  end

  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/member/products_controller.rb
class Member::ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page]).per(8)
  end

  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/login_helper.rb
module Admin::LoginHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/adminhomes_helper.rb
module AdminhomesHelper
end

app/helpers/adminmembers_helper.rb
module AdminmembersHelper
end

app/helpers/adminproducts_helper.rb
module AdminproductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/member/products_helper.rb
module Member::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/products/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="mt-5">商品編集</h1>
        <%= form_with model: @product,url: admin_product_path, local:true do |f| %>
        <table>
          <tbody>
            <tr>
              <td>
                <h4>商品画像</h4>
              </td>
              <td>
                <%= f.attachment_field :image %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>商品名</h4>
              </td>
              <td>
                <%= f.text_field :name %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>商品説明</h4>
              </td>
              <td>
                <%= f.text_area :introduction %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>ジャンル</h4>
              </td>
              <td>
                <%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>税抜価格</h4>
              </td>
              <td>
                <%= f.text_field :price %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>販売ステータス</h4>
              </td>
              <td>
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, '販売中', value: true %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, '販売停止中', value: false %>
                <%= f.submit '変更を保存' %>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h2><span class="badge badge-secondary">商品一覧</span></h2>
      <%= link_to new_admin_product_path do %>
        <div class="text-right">
          <button type="button" class="btn btn-light">  +  </button><%= link_to "新規登録" ,new_admin_product_path, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
 <div class= "col-md-8 offset-md-1">
  <table class="table">
   <thead>
     <tr>
       <th>商品ID</th>
       <th>商品名</th>
       <th>税抜価格</th>
       <th>ジャンル</th>
       <th>ステータス</th>
     </tr>
   </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= link_to product.name, admin_product_path(product) %></td>
        <td><%= product.price.to_s(:delimited) %></td>
        <td><%= product.genre.name %></td>
        <td>
          <% if product.is_active %>
           <p class="text-success">販売中</p>
          <% else %>
           <p class="text-muted">販売停止中</p>
          <% end %>
         </td>
       </tr>
      <% end %>
     </tbody>

   </table>
   <%= paginate @products %>
  </div>

 </div>

app/views/admin/products/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="mt-5">商品新規登録</h1>
        <%= form_with model: @product,url:admin_products_path, local:true do |f| %>
        <table>
          <tbody>
            <tr>
              <td><h4>商品画像</h4></td>
              <td><%= f.attachment_field :image %></td>
            </tr>
            <tr>
              <td><h4>商品名</h4></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><h4>商品説明</h4></td>
              <td><%= f.text_area :introduction %></td>
            </tr>
            <tr>
              <td><h4>ジャンル</h4></td>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
            </tr>
            <tr>
              <td><h4>税抜価格</h4></td>
              <td><%= f.text_field :price %></td>
            </tr>
            <tr>
              <td><h4>販売ステータス</h4></td>
              <td>
                <%= f.radio_button :is_active, '販売中' , checked: true %>
                <%= f.label :is_active, '販売中', value: true %>
                <%= f.radio_button :is_active, '販売停止中' %>
                <%= f.label :is_active, '販売停止中', value: false %>
                <%= f.submit '新規登録' %>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/products/search.html.erb
<div class="search-form">
  <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<div class="post-list">
  <% @products.each do |product| %>
    <%= product.name %>
  <% end %>
</div>

app/views/admin/products/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="mt-5">商品詳細</h1>
        <div class ="container">
          <div class="row">
            <div class="col-md-3">
              <%= attachment_image_tag @product, :image, format: 'jpeg',size: "100x100" %>
            </div>
            <div class="col-md-8 offset-md-1">
              <p>商品名：<%= @product.name %></p>
              <p>商品説明：<%= @product.introduction %></p>
              <p>ジャンル：<%= @product.genre.name %></p>
              <p>税抜価格：<%= @product.price.to_s(:delimited, delimiter: ',') %>円</p>
              <p>(税込価格):<%= (@product.price*1.1).round.to_s(:delimited, delimiter: ',') %>円</p>
              <p>販売ステータス：
              <% if @product.is_active == true %>
                <%= '販売中' %>
              <% else %>
                <%= '販売停止中' %></p>
              <% end %>
              <%= link_to "編集する", edit_admin_product_path(@product) %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>