config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"

 }


namespace :admin do
    get 'top' => 'homes#top'
    resources :members, only:[:index, :show, :edit, :update]

    resources :orders, only:[:index, :show, :update]



    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_details, only: [:update]
    get 'search' => 'products#search'
  end




  root 'member/homes#top'

  devise_for :member,skip: [:passwords,], controllers: {
  registrations: "member/registrations",
  sessions: 'member/sessions'
  }

  scope module: :member do
    resources :products, only: [:index, :show]
    get 'homes/about'
    get 'members/show'
    get 'members/edit'
    get 'members/unsubscribe'
    patch 'members/update'
    patch 'members/withdraw'
    delete "cart_products/destroy_all" => "cart_products#destroy_all"
    resources :cart_products, only: [:index, :create, :update, :destroy]
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]

    resources :products, only: [:index, :show]

    get "orders/new" => "orders#new"
    get "orders/confirm" => "orders#confirm"
    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:index, :show, :create]



  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_products, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders,dependent: :destroy

  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end


end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details,dependent: :destroy

    belongs_to :member

    has_many :products,through: :order_details,source: :product

    enum payment_method: { credit_card:0, transfer:1 }

    enum status: {
        payment_waiting:0,#入金待ち
        payment_confirmation:1,#入金確認
        in_production:2,#製作中
        preparing_delivery:3,#発送準備中
        delivered:4 #発送済み
    }

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  def index
  @members = Member.all.page(params[:page]).per(10)
  end

  def show
  @member = Member.find(params[:id])
  end

  def edit
  @member = Member.find(params[:id])
  end

  def update
  @member = Member.find(params[:id])
  @member.update(member_paramas)
  redirect_to admin_member_path(@member.id)
  end

  private
  def member_paramas
    params.require(:member).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:phone_number,:email,:address,:is_deleted)
  end



end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

     def index
       @orders = Order.page(params[:page]).per(10).reverse_order
     end

     def show
       @order = Order.find(params[:id])
       @order_products = @order.order_details
     end

     def update
       @order = Order.find(params[:id])
       @order.update(order_params)
       @order_products = @order.order_details
       if @order.status == "payment_confirmation"
          @order_products.each do |order_product|
            order_product.maiking_status = "production_pending"
            order_product.save
          end
       end
        redirect_to admin_order_path(@order.id)
     end


    private
        def order_params
          params.require(:order).permit(:status)
        end

        def order_details_params
          params.require(:order_details).permit(:maiking_status)
        end

end

app/controllers/member/cart_products_controller.rb
class Member::CartProductsController < ApplicationController
  def index
    @cart_products = CartProduct.all
  end

  def update
    @cart_product = CartProduct.find(params[:id])
    @cart_product.update(cart_product_params)
    redirect_to cart_products_path
  end
  
  def destroy_all
    cart_products = current_member.cart_products
    cart_products.destroy_all
    redirect_to cart_products_path
  end

  def destroy
    cart_product = CartProduct.find(params[:id])
    cart_product.destroy
    redirect_to cart_products_path
  end

  def create
    @cart_product = current_member.cart_products.new(cart_product_params)
    @cart_product.save
    redirect_to cart_products_path
  end

  private
  def cart_product_params
    params.require(:cart_product).permit(:product_id, :member_id, :amount)
  end

end

app/controllers/member/confirmations_controller.rb
# frozen_string_literal: true

class Member::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/member/homes_controller.rb
class Member::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/member/members_controller.rb
class Member::MembersController < ApplicationController

  def show
    @member = current_member
  end

  def edit
    @member = current_member
  end
  
  def update
  @member = current_member
  if @member.update(member_params)
      redirect_to members_show_path
  else
      render :edit
  end
  end

  def unsubscribe
    @member = Member.find_by(email: params[:email])
  end
  
  def withdraw
    @member = current_member
    @member.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  private

  def member_params
    params.require(:member).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :address, :postal_code, :phone_number)
  end
  

end

app/controllers/member/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Member::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
  def new
    @order = Order.new
    @member = current_member
    @addresses = @member.shipping_addresses
  end

  def create
  	member = current_member
  	# sessionを使ってデータを一時保存
  	session[:order] = Order.new
  	cart_products = current_member.cart_products

  	# total_paymentのための計算
  	sum = 0
  	cart_products.each do |cart_product|
  		sum += (cart_product.product.add_tax_price).floor * cart_product.amount
  	end

  	session[:order][:postage] = 800
  	#送料込みの合計金額
  	session[:order][:billing_amount] = sum + session[:order][:postage]
  	#注文ステータス
  	session[:order][:status] = 0
  	session[:order][:member_id] = current_member.id
  	# ラジオボタンで選択された支払方法のenum番号を渡している
  	session[:order][:payment_method] = params[:payment_method].to_i

  	# ラジオボタンで選択されたお届け先によって条件分岐
  	destination = params[:a_method].to_i
  	# ご自身の住所が選択された時
  	if destination == 0
  		session[:order][:postal_code] = member.postal_code
  		session[:order][:address] = member.address
  		session[:order][:name] = member.last_name + member.first_name
  		# 登録済住所が選択された時
  	elsif destination == 1
  		address = ShippingAddress.find(params[:address_for_order])
  		session[:order][:postal_code] = address.postal_code.to_i
  		session[:order][:address] = address.address
  		session[:order][:name] = address.name
  	# 新しいお届け先が選択された時
  	elsif destination == 2
  		session[:new_address] = 2
  		session[:order][:postal_code] = params[:postal_code].to_i
  		session[:order][:address] = params[:address]
  		session[:order][:name] = params[:name]
  	end
  	# お届け先情報に漏れがあればリダイレクト
  	if session[:order][:postal_code].presence && session[:order][:address].presence && session[:order][:name].presence
      redirect_to orders_confirm_path
  	else
  		flash[:alert] = 'お届け先情報を入力してください'
  		redirect_to orders_new_path
  	end
  end

  def confirm
    @cart_products = current_member.cart_products.page(params[:page]).per(4)
  end


  def complete
  	order = Order.new(session[:order])
	  order.save

		# 新しいお届け先を自動で保存
		if session[:new_address]
			address = current_member.shipping_addresses.new
			address.postal_code = order.postal_code
			address.address = order.address
			address.name = order.name
			address.save
			session[:new_address] = nil
		end
		# 以下、order_detail(中間テーブル)作成
		cart_products = current_member.cart_products
		cart_products.each do |cart_product|
		order_detail = OrderDetail.new
		order_detail.order_id = order.id
		order_detail.product_id = cart_product.product.id
		order_detail.amount = cart_product.amount
		order_detail.maiking_status = 0
		order_detail.price = (cart_product.product.add_tax_price).floor
		order_detail.save
		end
		session.delete(:order)
		session[:order] = nil
		# 購入後はカート内商品削除
		cart_products.destroy_all
  end

  def index
  	@orders = current_member.orders.page(params[:page]).per(6)
  end

  def show
  	@order = Order.find(params[:id])
  	@order_details = @order.order_details
  end

end

app/controllers/member/passwords_controller.rb
# frozen_string_literal: true

class Member::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/member/products_controller.rb
class Member::ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page]).per(8)
  end

  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
  end
end

app/controllers/member/registrations_controller.rb
# frozen_string_literal: true

class Member::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/member/sessions_controller.rb
# frozen_string_literal: true

class Member::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :member_state, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  
  
  protected
  
  def member_state
    @member = Member.find_by(email: params[:member][:email])
    return if !@member
    if @member.valid_password?(params[:member][:password])
      if @member.is_deleted == true
       redirect_to new_member_registration_path
      end
    end
  end
  
end

app/controllers/member/shipping_addresses_controller.rb
class Member::ShippingAddressesController < ApplicationController
  def index
    @shipping_address = ShippingAddress.new
    @shipping_addresses = current_member.shipping_addresses
  end

  def create
    @shipping_address = ShippingAddress.new(shipping_params)
    @shipping_address.member_id = current_member.id
    # バリデーションつけたらif文を書く
    @shipping_address.save
    redirect_to shipping_addresses_path
  end

  def edit
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def update
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.update(shipping_params)
    redirect_to shipping_addresses_path
  end

  def destroy
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.destroy
    redirect_to shipping_addresses_path
  end

  private
  def shipping_params
    params.require(:shipping_address).permit(:name, :postal_code, :address)
  end

end

app/controllers/member/unlocks_controller.rb
# frozen_string_literal: true

class Member::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/member/cart_products_helper.rb
module Member::CartProductsHelper
end

app/views/member/orders/complete.html.erb
<div class = "container">
  <div class = "row">
    <div class="px-3 mx-auto  mt-5">
        <h3 style="text-align:center">
          ご注文ありがとうございました!!
        </h3>
    </div>
        <div class="thanks_image offset-2" style="height: 400px;"></div>
  </div>
</div>

app/views/member/orders/confirm.html.erb
<div class="container mt-5">

  <div class="row"><h4 class="p-2 mb-5 heading_background_color">注文情報確認</h4></div>

  <div class="row">

    <div class="col">
      <table class="table table-bordered border-secondary ">
        <thead class="table-secondary">
          <tr><th>商品名</th><th>単価(税込)</th><th>数量</th><th>小計</th></tr>
        </thead>
        <tbody>
          <% sum = 0 %>
          <% @cart_products.each do |cart_item| %>
            <tr>
              <td><%= attachment_image_tag cart_item.product, :image, format: "jpeg", fallback: "no_image.jpg", size: "80x60",class:"mr-3" %><%= cart_item.product.name %></td>
              <td class="align-middle"><%= cart_item.product.add_tax_price.to_s(:delimited) %>円</td>
              <td class="align-middle"><%= cart_item.amount %></td>
              <td class="align-middle"><%= (cart_item.amount*cart_item.product.price*1.1).round.to_s(:delimited) %>円</td>
              <% sum += cart_item.amount*cart_item.product.price*1.1 %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @cart_products %>
    </div>

    <div class="col-md-3 billing">
      <table class="table table-bordered border-primary">
       <!-- sessiomのデータを表示する場合、カラム名に""つける -->
          <tr><td class="font-weight-bold table-secondary">配送料</td><td><%= session[:order]["postage"].to_s(:delimited) %>円</td></tr>
          <tr><td class="font-weight-bold table-secondary">商品合計</td><td><%= sum.round.to_s(:delimited) %>円</td></tr>
          <tr><td class="font-weight-bold table-secondary">請求金額</td><td><%= session[:order]["billing_amount"].to_s(:delimited) %>円</td></tr>
      </table>
    </div>

  </div>

  <div class="row">

      <table class="table table-borderless">
        <tr>
          <th  class="info" style="width: 20%">支払方法</th>
          <td class="text-left">
            <% if session[:order]["payment_method"] == 'transfer' %>
             <%= '銀行払い' %>
            <% else %>
             <%= 'クレジットカード' %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th  class="info" style="width: 20%">お届け先</th>
          <td class="text-left">
            〒<%= session[:order]["postal_code"] %><br>
            <%= session[:order]["address"] %><br>
            <%= session[:order]["name"]  %>
          </td>
        </tr>
      </table>
  </div>

  <div class="row justify-content-center mb-2"><%= link_to "購入を確定する", orders_complete_path, class: 'btn btn-success btn-lg' %></div>

</div>

app/views/member/orders/index.html.erb
<body>
  <div class="container">
    <div class="row">

          <h4 class="mb-4 text-color col-3 text-center  pt-4 rounded-pill heading_background_color">注文履歴一覧</h4>
          <div class="col-7 order_index_image offset-1"></div>

    </div>
    <div class="row">
      <div class="col">
          <table class="table table-bordered border-dark col-12 mt-3 mb-5">
              <tr class="table-color">
                  <th class="table-active">注文日</th>
                  <th class="table-active">配送先</th>
                  <th class="table-active">注文商品</th>
                  <th class="table-active">支払い金額</th>
                  <th class="table-active">ステータス</th>
                  <th class="table-active">注文詳細</th>
              </tr>
              <% @orders.each do |order| %>
              <tr>
                  <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                  <td><%= order.postal_code %><br><%= order.address %><br><%= order.name %></td>
                  <td>
                      <% order.order_details.each do |order_detail| %>
                      <%= order_detail.product.name %><br>
                      <% end %>
                  </td>
                  <td><%= order.billing_amount.to_s(:delimited) %>円</td>
                  <td><%= order.status_i18n %></td>
                  <td><%= link_to "表示する", order_path(order) ,class: "btn btn-primary btn-sm" %></td>
              </tr>
              <% end %>
          </table>
          <%= paginate @orders %>
      </div>
    </div>
  </div>
</body>

app/views/member/orders/new.html.erb
<div class="container mt-5">
 <%= flash[:alert] %>
 <div class="row mb-5">
  <h4 class="under p-2 heading_background_color">注文情報入力</h4>
 </div>
</div>
<%= form_with(url: orders_path, method: :post, local:true) do |form| %>
 <div class="container ">
   <div class="form-group row mt-4">
     <h5 class="col-sm-3"><strong>支払方法</strong></h5>
   </div>
   <div class="form-group row ">
  			<!-- form.radio_button :カラム名, :保存される値(enumの番号) -->
        <h5 class="col-sm-3 mx-5">
        <%= form.radio_button :payment_method, 0 ,checked: true%>
        <%= form.label :payment_method_credit_card, 'クレジットカード' %>
        </h5>
        <h5 class="col-sm-3 mx-5">
        <%= form.radio_button :payment_method, 1 %>
        <%= form.label :payment_method_transfer, '銀行払い' %>
        </h5>
   </div>

 <div class="form-group row ">
   <h5 class="col-sm-2 "><strong>お届け先</strong></h4>
 </div>
 <div class="form-group row mb-5">
   <h5 class="col-sm-3 mx-5"><%= form.radio_button :a_method, 0 ,checked: true %>
   <%= form.label :ご自身の住所 %></h5>
   <div class="col-sm-9"></div>
   <h6 class=" offset-sm-1 col-sm-6">〒<%= @member.postal_code %>
   <%= @member.address %></br>
   <%= @member.full_name %></h6>
 </div>

 <div class="form-group row mb-5">
   <h5 class="col-sm-3 mx-5"><%= form.radio_button :a_method, 1 %>
   <%= form.label :登録済住所から選択 %></h5>
   <div class="col-sm-9"></div>
   <div class="offset-sm-1 col-sm-8">
     <% if !@addresses.present? %>
       <p><%= link_to "配送先", shipping_addresses_path %>が登録されていません<br>下記の新しいお届け先を選択、入力し注文確定されると自動的にその住所が配送先へ登録されます</p>
     <% else %>
       <%= form.collection_select :address_for_order, @addresses, :id, :address_all, include_blank: " 登録してある配送先住所から選択", size: "100x75" %>
     <% end %>
   </div>
 </div>

 <div class="form-group row ">
   <h5 class="col-sm-3 mx-5"><%= form.radio_button :a_method, 2 %>
   <%= form.label :新しいお届け先 %></h5>
   <div class="col-sm-9"></div>
 </div>

 <div class="form-group row ">
  <div class="input-group">
   <div class="offset-sm-1 col-sm-3 input-gruop-append"><%= form.label :"郵便番号(ハイフンなし)", class: "col-xs-3 control-label"  %></div>
   <div class="col-3 input-gruop-append"><%= form.text_field :postal_code, class: "col-xs-4 form-control-static postal_code" %></div>
  </div>
 </div>

 <div class="form-group row mt-2">
  <div class="input-group">
   <div class="offset-sm-1 col-sm-3 input-gruop-append"><%= form.label :"住所", class: "col-xs-3 control-label" %></div>
   <div class="col-8 input-gruop-append"><%= form.text_field :address, class: "col-8 form-control-static address" %></div>
  </div>
 </div>

 <div class="form-group row mt-2">
  <div class="input-group">
   <div class="offset-sm-1 col-sm-3 input-gruop-append"><%= form.label :"宛名", class: "col-xs-3 control-label" %></div>
   <div class="col-sm-3 input-gruop-append"><%= form.text_field :name, class: "col-xs-4 form-control-static name"%></div>
  </div>
 </div>

  <div class="row my-5">
  <div class="col-sm-5"></div>
  <div class="col-sm-3"><%= form.submit "確認画面へ進む", class: 'btn btn-success btn-lg'%></div>
  <% end %>
  </div>
</div>

app/views/member/orders/show.html.erb
<body>
  <div class="container">

    <div class="row mb-3">

        <h4 class="mb-4 text-color col-md-3 text-center pt-4 rounded-pill heading_background_color">注文履歴詳細</h4>
        <div class="col-7 order_show_image offset-1"></div>

    </div>
          <div class="row">
            <div class="col-7"><p class="font-weight-bold">注文情報</p></div>
            <div class="col-3"><p class="font-weight-bold ml-3">請求情報</p></div>
          <table class="table table-bordered border-dark col-7">

                  <tr>
                      <th class="table-active table-color col-3">注文日</th>
                      <th><%= @order.created_at.strftime('%Y/%m/%d') %></th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">配送先</th>
                    <th><%= @order.postal_code %><br><%= @order.address %><br><%= @order.name %></th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">支払い方法</th>
                    <th><%= @order.payment_method_i18n %></th>
                  </tr><tr>
                    <th class="table-active table-color">ステータス</th>
                    <th><%= @order.status_i18n %></th>
                  </tr>
          </table>
          <table class="table table-bordered border-dark col-3 ml-3 h-75">
                  <tr>
                      <th class="table-active table-color">商品合計</th>
                      <th><%= @order.billing_amount - @order.postage %>円</th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">配送料</th>
                    <th><%= @order.postage %>円</th>
                  </tr>
                  <tr>
                    <th class="table-active table-color">ご請求額</th>
                    <th><%= @order.billing_amount %>円</th>
                  </tr>
          </table>
          </div>

          <div class="row"><p class="font-weight-bold table-color">注文内容</p></div>
          <table class="table table-bordered border-dark col-9 mt-3 mb-5">
              <tr class="table-color">
                  <th class="table-active  col-6">商品</th>
                  <th class="table-active">単価（税込）</th>
                  <th class="table-active">個数</th>
                  <th class="table-active">小計</th>
              </tr>
              <% @order_details.each do |order_details| %>
              <tr>
                  <th><%= order_details.product.name %></th>
                  <th><%= order_details.product.add_tax_price %>円</th>
                  <th><%= order_details.amount %>個</th>
                  <th><%= (order_details.amount*order_details.product.add_tax_price).round.to_s(:delimited) %>円</th>
              </tr>
              <% end %>
          </table>
      </div>
    </div>
  </div>
</body>